[package]
name = "ans"
version = "0.1.0"
authors = ["Arc Asumity <arcasumity@hotmail.com>"]
license = "GPL-3.0-or-later"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
